// Generated by CoffeeScript 1.4.0
(function() {
  var RedisStore, app, engine, express, http, logger, path, routes;

  express = require('express');

  http = require('http');

  path = require('path');

  engine = require('ejs-locals');

  RedisStore = require('connect-redis')(express);

  process.env.NODE_ENV = "development";

  app = express();

  routes = require('./lib/routes')(app);

  logger = require('./lib/logger').factory();

  logger.log('info', 'Starting app in ' + process.env.NODE_ENV + ' mode...');

  app.engine('ejs', engine);

  app.configure(function() {
    app.set('port', process.env.PORT || 3000);
    app.set('views', __dirname + '/views');
    app.set('view engine', 'ejs');
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.compress());
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express.cookieParser());
    app.use(express.session({
      secret: "pileated woodpecker",
      expires: new Date(Date.now() + (2 * 60 * 60 * 1000))
    }));
    app.use(app.router);
    app.use(express["static"](path.join(__dirname, 'public')));
    app.use(function(err, req, res, next) {
      return res.status(err.status || 500).render('error', {
        title: 'Error',
        description: err.message
      });
    });
    return app.use(function(req, res, next) {
      return res.status(404).render('error', {
        title: 'Error 404',
        description: 'The page you requested cannot be found.'
      });
    });
  });

  app.configure('development', function() {
    return app.use(express.errorHandler());
  });

  http.createServer(app).listen(app.get('port'), function() {
    return console.log("Express server listening on port " + app.get('port'));
  });

}).call(this);
