// Generated by CoffeeScript 1.6.1
(function() {
  var User, auth, bcrypt;

  bcrypt = require('bcrypt');

  auth = require('../lib/auth');

  User = require('../models/users.js');

  exports.login = function(req, res) {
    auth.ssl_required(req, res, true);
    res.render('auth/login', {
      locals: {
        title: 'Login',
        flash: req.flash()
      }
    });
  };

  exports.authenticate = function(req, res) {
    var password, username;
    auth.ssl_required(req, res, true);
    username = req.body.username;
    password = req.body.password;
    User.findOne({
      username: username
    }, function(err, user) {
      if (err) {
        req.flash("error", "Invalid username/password combination.");
        res.redirect('/auth/login');
        return;
      }
      return bcrypt.compare(password, user.password, function(err, same) {
        if (err) {
          req.flash("error", "An error occurred.");
          res.redirect('/auth/login');
          return;
        }
        if (!same) {
          req.flash("error", "Invalid username/password combination.");
          res.redirect('/auth/login');
          return;
        } else {
          req.flash("error", "Welcome, " + username + ".");
          req.session.auth = true;
          req.session.username = username;
          res.locals.authenticated = true;
          res.locals.username = username;
          res.redirect('/content/menu');
          return;
        }
      });
    });
  };

  exports.logout = function(req, res) {
    req.session.regenerate(function() {
      res.redirect('/auth/login');
    });
  };

}).call(this);
