// Generated by CoffeeScript 1.6.1
(function() {
  var auth;

  auth = require('../lib/auth');

  exports.index = function(req, res) {
    auth.ssl_required(req, res, false);
    res.render('static-content/nodejs', {
      title: 'Node.js'
    });
  };

}).call(this);
