// Generated by CoffeeScript 1.6.1
(function() {
  var auth;

  auth = require('../lib/auth');

  exports.nodejs = function(req, res) {
    auth.ssl_required(req, res, false);
    return res.render('static-content/nodejs', {
      title: 'Node.js'
    });
  };

  exports.menu = function(req, res) {
    auth.ssl_required(req, res, true);
    auth.auth_required(req, res);
    return res.render('static-content/menu', {
      title: 'Menu',
      flash: req.flash()
    });
  };

}).call(this);
