// Generated by CoffeeScript 1.6.1
(function() {
  var User, auth;

  User = require('../models/users.js');

  auth = require('../lib/auth');

  exports.index = function(req, res) {
    auth.ssl_required(req, res, true);
    auth.auth_required(req, res);
    User.find({}, function(err, users) {
      console.log(users);
      res.render('users/index', {
        title: 'Users',
        users: users,
        flash: req.flash()
      });
    });
  };

  exports.destroy = function(req, res) {
    var id;
    auth.ssl_required(req, res, true);
    auth.auth_required(req, res);
    id = req.params.id;
    User.remove({
      _id: id
    }, function(err) {
      if (err) {
        req.flash("error", "Invalid user id.");
        res.redirect('/users/index');
      } else {
        req.flash("error", "User deleted.");
        res.redirect('/users/index');
      }
    });
  };

}).call(this);
