// Generated by CoffeeScript 1.6.1
(function() {

  exports.ssl_required = function(req, res, required) {
    if (process.env.NODE_ENV === 'production') {
      if (required) {
        if (req.headers['x-forwarded-proto'] !== 'https') {
          res.redirect('https://node.moore-database.com' + req.url);
        }
      } else {
        if (req.headers['x-forwarded-proto'] === 'https') {
          res.redirect('http://node.moore-database.com' + req.url);
        }
      }
    }
    return true;
  };

  exports.auth_required = function(req, res) {
    if (req.session.auth !== true) {
      res.redirect("/auth/login");
      return;
    }
    return true;
  };

}).call(this);
