// Generated by CoffeeScript 1.4.0
(function() {

  exports.ssl_required = function(req, res) {
    if (req.headers['x-forwarded-proto'] !== 'https') {
      if (process.env.NODE_ENV === 'production') {
        res.redirect('https://node.moore-database.com' + req.url);
      }
    }
    return true;
  };

  exports.ssl_not_required = function(req, res) {
    if (req.headers['x-forwarded-proto'] === 'https') {
      if (process.env.NODE_ENV === 'production') {
        res.redirect('http://node.moore-database.com' + req.url);
      }
    }
    return true;
  };

}).call(this);
