// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(ejs) {
    var moment;
    moment = require('moment');
    ejs.filters.dateFormatLong = function(date) {
      return moment(date, "YYYY-MM-DD HH:mm:ss");
    };
  };

}).call(this);
