// Generated by CoffeeScript 1.6.1
(function() {

  module.exports = function(ejs) {
    var moment;
    moment = require('moment');
    return ejs.filters.dateFormatLong = function(date) {
      return moment(date).format("YYYY-MM-DD HH:mm:ss");
    };
  };

}).call(this);
