// Generated by CoffeeScript 1.4.0
(function() {
  var winston;

  winston = require('winston');

  exports.factory = function() {
    var logger;
    logger = new winston.Logger({
      transports: [
        new winston.transports.File({
          filename: './error.log',
          handleExceptions: true,
          json: true
        })
      ]
    });
    return logger;
  };

}).call(this);
