// Generated by CoffeeScript 1.4.0
(function() {
  var db, mongoose, uristring;

  mongoose = require("mongoose");

  uristring = process.env.MONGOLAB_URI || 'mongodb://localhost/local';

  mongoose.connect(uristring, function(err, res) {
    if (err) {
      return console.log('ERROR connecting to: ' + uristring + '. ' + err);
    }
  });

  db = mongoose.connection;

  db.on('error', console.error.bind(console, 'Connection error:'));

  db.once('open', function() {
    var User, newUser, salt, userSchema;
    userSchema = mongoose.Schema({
      username: {
        type: String,
        require: true,
        trim: true,
        unique: true
      },
      password: {
        type: String,
        require: true
      }
    });
    User = mongoose.model('User', userSchema);
    User.remove({}, function(err) {
      if (err) {
        return console.log('Error deleting old data.');
      }
    });
    /*
      admin / 28rTu932Ypxz987
      pickpocket23bazooka / dY78vNqP37sS94U
      stephenmoore56 / Ty84Db0U6qM33
    */

    salt = bcrypt.genSaltSync(10);
    newUser = new User({
      username: 'admin',
      password: bcrypt.hashSync("28rTu932Ypxz987", salt)
    });
    newUser.save();
    newUser = new User({
      username: 'pickpocket23bazooka',
      password: bcrypt.hashSync("dY78vNqP37sS94U", salt)
    });
    newUser.save();
    newUser = new User({
      username: 'stephenmoore56',
      password: bcrypt.hashSync("Ty84Db0U6qM33", salt)
    });
    newUser.save();
    return console.log('Added three users.');
  });

}).call(this);
