// Generated by CoffeeScript 1.6.1
(function() {
  var _;

  _ = require('underscore');

  module.exports = function(app) {
    var auth, birding, content, controllers, users;
    controllers = require('../controllers');
    content = _.extend(require('../controllers/static-content'));
    controllers.content = content;
    birding = _.extend(require('../controllers/birding'));
    controllers.birding = birding;
    auth = _.extend(require('../controllers/auth'));
    controllers.auth = auth;
    users = _.extend(require('../controllers/users'));
    controllers.users = users;
    app.get('/', controllers.content.nodejs);
    app.get('/content', controllers.content.nodejs);
    app.get('/content/nodejs', controllers.content.nodejs);
    app.get('/birding', controllers.birding.orders);
    app.get('/birding/orders', controllers.birding.orders);
    app.get('/birding/ordersajax', controllers.birding.ordersajax);
    app.get('/birding/ordersjson', controllers.birding.ordersjson);
    app.get('/birding/months', controllers.birding.months);
    app.get('/birding/monthsjson', controllers.birding.monthsjson);
    app.get('/logout', controllers.auth.logout);
    app.get('/auth/login', controllers.auth.login);
    app.post('/auth/login', controllers.auth.authenticate);
    app.get('/login', controllers.auth.login);
    app.get('/logout', controllers.auth.logout);
    app.get('/auth/logout', controllers.auth.logout);
    app.get('/content/menu', controllers.content.menu);
    app.get('/users', controllers.users.index);
    app.get('/users/index', controllers.users.index);
    app.get('/users/destroy/:id', controllers.users.destroy);
    app.get('/users/add', controllers.users.add);
    app.post('/users/create', controllers.users.create);
    app.get('/users/edit/:id', controllers.users.edit);
    app.post('/users/update', controllers.users.update);
  };

}).call(this);
