// Generated by CoffeeScript 1.4.0
(function() {
  var _;

  _ = require('underscore');

  module.exports = function(app) {
    var auth, birding, content, controllers;
    controllers = require('../controllers');
    content = _.extend(require('../controllers/static-content'));
    controllers.content = content;
    birding = _.extend(require('../controllers/birding'));
    controllers.birding = birding;
    auth = _.extend(require('../controllers/auth'));
    controllers.auth = auth;
    app.get('/', controllers.content.nodejs);
    app.get('/content', controllers.content.nodejs);
    app.get('/content/nodejs', controllers.content.nodejs);
    app.get('/birding', controllers.birding.orders);
    app.get('/birding/orders', controllers.birding.orders);
    app.get('/birding/ordersajax', controllers.birding.ordersajax);
    app.all('*', function(req, res, next) {
      if (req.headers['x-forwarded-proto'] !== 'https') {
        return res.redirect('https://node.moore-database.com' + req.url);
      } else {
        return next();
      }
    });
    app.get('/auth/login', controllers.auth.login);
    app.post('/auth/login', controllers.auth.authenticate);
    app.get('/login', controllers.auth.login);
    return app.get('/content/menu', controllers.content.menu);
  };

}).call(this);
